I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 109, in script
    if EVAtt > 0:
  File "game/scripts/script.rpy", line 109, in <module>
    if EVAtt > 0:
NameError: name 'EVAtt' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 109, in script
    if EVAtt > 0:
  File "C:\Users\qwawe\Downloads\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\qwawe\Downloads\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\qwawe\Downloads\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scripts/script.rpy", line 109, in <module>
    if EVAtt > 0:
NameError: name 'EVAtt' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Novel_URFU_22 1.0
Sat Dec 31 15:35:30 2022
